from setuptools import setup, find_packages

setup(
    name="liahr",
    packages=find_packages(),
    install_requires=[
        "torch",
        "transformers",
        "gridparse",
        "langcodes",
        "language_data",
        "pandas",
        "scikit-learn",
        "openai",
        "tenacity",
        "python-dotenv",
        "ekphrasis",
        "accelerate",
        "bitsandbytes",
        "sentence-transformers",
        "matplotlib",
        "seaborn",
        "nltk",
        "gensim",
        "ai2-olmo",
        "datasets",
        "trl",
        "peft",
        "vllm",
        "liger-kernel",
        "openpyxl",
    ],
    extras_require={"dev": ["black", "pytest"]},
)
