root_dir: /path/to//goemotions
train_splits: train
test_splits: dev
instruction_prompt: ./configs/GoEmotions/instruction.txt
incontext_prompt: ./configs/GoEmotions/incontext.txt
system_prompt: ./configs/GoEmotions/system.txt
max_new_tokens: 30
accelerate: True
logging_level: debug
text_preprocessor: False